<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Description>Polhem.OAuth2.AspNet is an OAuth2 authentication library designed for ASP.NET WebForms / MVC, supporting Google, Facebook, LINE, Azure, and Auth0.</Description>
    <PackageTags>OAuth2 ASP.NET WebForms/MVC</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polhem.OAuth2\Polhem.OAuth2.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web" />
  </ItemGroup>

</Project>
